import Head from "next/head";
import Image from "next/image";
import styles from "../styles/home.module.scss";
import { useState, useEffect } from "react";
import Loader from "../components/Loader";
import { useRouter } from "next/router";
import axios from "axios";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const router = useRouter();

  useEffect(() => {
    if (typeof window != undefined) {
      const accessToken = localStorage.getItem("accessToken");
      if (!accessToken) {
        setLoading(false);
        setUser(null);
      } else {
        axios
          .get(`${process.env.NEXT_PUBLIC_SERVER_URL}/auth/me`, {
            headers: {
              Authorization: accessToken,
            },
          })
          .then((res) => {
            if (res.data.success) {
              setLoading(false);
              setUser(res.data.user);
            } else {
              setLoading(false);
              setUser(null);
            }
          });
      }
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>MetaHub OAuth Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <div
          style={{
            height: "100vh",
            width: "100%",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Loader center={true} />
        </div>
      ) : (
        <div
          style={{
            height: "100vh",
            width: "100%",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          {user ? (
            <div className={styles.user}>
              <img src={user.avatar} />
              <p>
                {user.username}#{user.tag}
              </p>
              <span>DOB: {user.dob}</span>
              <div>{user.reports.length} Reports</div>
            </div>
          ) : (
            <button
              className={styles["login-button"]}
              onClick={() => {
                console.log("hey");
                router.push(
                  `${process.env.NEXT_PUBLIC_OAUTH_URL}/oauth/authorize?clientId=${process.env.NEXT_PUBLIC_CLIENT_ID}`
                );
              }}
            >
              Login using MetaHub
            </button>
          )}
        </div>
      )}
    </div>
  );
}
